### ISSUE TITLE
Cannot find module 'replace-in-file

### ISSUE THREAD

**Issue by osmaczko** [birgersp/vscode-cpp-header-refactor#2]
VS code fails to activate the extension.

```
[exthost] [error] Activating extension birgersp.cpp-header-refactor failed due to an error:
[exthost] [error] Error: Cannot find module 'replace-in-file'
```

**Comment by birgersp** [comment]
Thanks.

Maybe the 'replace-in-file' dependency is incorrectly added to the project. It should probably be a runtime dependency, rather than dev dependency which it currently is.

Not sure when I'll have time to fix.

**Comment by birgersp** [comment]
As mentioned in the readme I am very much open for PRs. If someone wants to fix this then be my guest :)

**Comment by ollbx** [comment]
Is there some workaround outside of fixing the code for this? Unfortunately I don't have enough experience with js/ts development to fix the problem, but I could really use this extension.

**Comment by birgersp** [comment]
I'll try to get this fixed later today

**Comment by birgersp** [comment]
I have published a new version, the issue should be fixed now.
